### ISSUE TITLE
Issue in Terminal mode 

### ISSUE THREAD

**Issue by poorvasha** [Navayuvan-SB/Auto-Logger#2]
### Issue 1 
After I have been Switched to Terminal mode I tried a command.,

> sudo apt update

It threw an error : 

` File "./log", line 273, in <module>
    terminal()
  File "./log", line 175, in terminal
    text_to_write = dt_string + " \t " + "Command: " + cmd[2:] + "\n"
TypeError: must be str, not list`

### Issue 2
whatever the command or text I type in terminal mode are invisible.

`

**Comment by Navayuvan-SB** [comment]
@poorvasha Yeah, Sorry for that. It's fixed in latest build. Please clone and Reinstall the Application.
